// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scsujnkdqrlqgsqntmeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjc3VqbmtkcXJscWdzcW50bWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzEzODksImV4cCI6MjA3MzQwNzM4OX0.gLKCsFIhsevG6mj8sZO5hZkkQZyjyLwxXVSFuODSbxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});